language: cpp
compiler:
  - gcc
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libqt4-core libqt4-gui libqt4-dev qt4-dev-tools qt4-qmake
  - sudo pip install cpp-coveralls
script:
  - make
env:
  - TARGET=sim
after_success:
  - coveralls --exclude lib --exclude tests --gcov-options '\-lp'
